2023-09-19 12:51:21,548 - root - INFO - Using device: cuda
2023-09-19 12:51:21,562 - root - INFO - GRID A100D-20C
2023-09-19 12:51:21,562 - root - INFO - Memory Usage:
2023-09-19 12:51:21,562 - root - INFO - Allocated: 0.0 GB
2023-09-19 12:51:21,563 - root - INFO - Cached: 0.0 GB
Traceback (most recent call last):
  File "/home/ubuntu/finger-vein-quality-assessement/common/data_pipeline/dataset.py", line 56, in get_classes
    classes = os.listdir(self.get_directory() + "/train")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/layer3output/train'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ubuntu/finger-vein-quality-assessement/train.py", line 137, in <module>
    main()
  File "/home/ubuntu/finger-vein-quality-assessement/train.py", line 121, in main
    train(
  File "/home/ubuntu/finger-vein-quality-assessement/common/train_pipeline/train.py", line 158, in train
    train_dataset, validation_dataset, _ = get_dataset(environment, batch_size)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/finger-vein-quality-assessement/common/train_pipeline/train.py", line 45, in get_dataset
    common_dataset(
  File "/home/ubuntu/finger-vein-quality-assessement/common/data_pipeline/dataset.py", line 38, in __init__
    self.classes: List[str] = self.get_classes()
                              ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/finger-vein-quality-assessement/common/data_pipeline/dataset.py", line 58, in get_classes
    classes = os.listdir(self.get_directory())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/layer3output'